version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z
    container_name: gitlab-redis

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-24
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    container_name: gitlab-postgresql

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.10.2
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=

    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=
    container_name: gitlab

  runner-docker-in-docker:
    restart: always
    image: sameersbn/gitlab-ci-multi-runner:latest
    depends_on:
    - gitlab
    volumes:
    - /srv/docker/gitlab-runner/docker-in-docker:/home/gitlab_ci_multi_runner/data
    links:
    - gitlab:gitlab
    environment:
    - CI_SERVER_URL=http://172.17.0.1:10080/ci
    - RUNNER_TOKEN=dzuZiJ3hsUaTNoKYghbd
    - RUNNER_DESCRIPTION=docker-in-docker-runner
    - RUNNER_EXECUTOR=docker
    - DOCKER_IMAGE=docker:latest
    - DOCKER_PRIVILEGED=true
    - DOCKER_EXTRA_HOSTS=localhost:172.17.0.1
    container_name: gitlab-runner-docker-in-docker

  runner-docker-socket-binding:
    restart: always
    image: sameersbn/gitlab-ci-multi-runner:latest
    depends_on:
    - gitlab
    volumes:
    - /srv/docker/gitlab-runner/docker-socket-binding:/home/gitlab_ci_multi_runner/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /git/devlee/registry/nginx/volumes:/etc/docker/cert.d
    links:
    - gitlab:gitlab
    environment:
    - CI_SERVER_URL=http://172.17.0.1:10080/ci
    - RUNNER_TOKEN=dzuZiJ3hsUaTNoKYghbd
    - RUNNER_DESCRIPTION=docker-socket-binding-runner
    - RUNNER_EXECUTOR=docker
    - DOCKER_IMAGE=docker:latest
    - DOCKER_EXTRA_HOSTS=localhost:172.17.0.1
    - DOCKER_VOLUMES=/git/devlee/registry/nginx/volumes:/etc/docker/cert.d
    container_name: gitlab-runner-docker-socket-binding
    extra_hosts:
    - "localhost:172.17.0.1"
    - "docker-registry:172.17.0.1"

  runner-shell:
    restart: always
    image: sameersbn/gitlab-ci-multi-runner:latest
    depends_on:
    - gitlab
    volumes:
    - /srv/docker/gitlab-runner/shell:/home/gitlab_ci_multi_runner/data
    links:
    - gitlab:gitlab
    environment:
    - CI_SERVER_URL=http://172.17.0.1:10080/ci
    - RUNNER_TOKEN=dzuZiJ3hsUaTNoKYghbd
    - RUNNER_DESCRIPTION=shell-runner
    - RUNNER_EXECUTOR=shell
    container_name: gitlab-runner-shell